[env:esp32s3box]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200

lib_deps =
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    mobizt/ESP Mail Client
    arduino-libraries/Stepper

lib_ignore =
    ESPAsyncTCP
    RPAsyncTCP